[buildPlans.iosevka-hex]
family = "Iosevka Hex"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.iosevka-hex.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-d = "more-rounded-serifless"
zero = "unslashed"
one = "base"
two = "curly-neck"
four = "open"

[buildPlans.iosevka-hex.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-hex.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ryanc]
family = "Iosevka RyanC"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-ryanc.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-d = "more-rounded-serifless"
g = "double-storey"
i = "hooky"
k = "straight-serifless"
l = "serifed-flat-tailed"
y = "straight-turn"
zero = "slashed"
one = "base"
four = "closed"
six = "closed-contour"
nine = "closed-contour"
asterisk = "penta-low"
caret = "low"
number-sign = "upright"
at = "threefold"
dollar = "through"
percent = "rings-continuous-slash"

[buildPlans.iosevka-ryanc.variants.italic]
g = "single-storey-serifless"
i = "tailed-serifed"

[buildPlans.iosevka-ryanc.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-ryanc.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-ryanc.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ryanc.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-ryanc.widths.normal]
shape = 500
menu = 5
css = "normal"
