[buildPlans.iosevka-hex]
family = "Iosevka Hex"
spacing = "normal"
serifs = "sans"
noCvSs = true
noLigation = true

[buildPlans.iosevka-hex.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-d = "more-rounded-serifless"
zero = "unslashed"
one = "base"
two = "curly-neck-serifless"
four = "open-serifless"

[buildPlans.iosevka-hex.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-hex.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.template-sans]
family = "Template Sans"
spacing = "normal"
serifs = "sans"

[buildPlans.template-sans.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hooked"
g = "double-storey"
i = "hooky"
l = "serifed-semi-tailed"
m = "short-leg-serifless"
w = "straight-serifless"
x = "straight-serifless"
y = "straight-turn-serifless"
long-s = "flat-hook-middle-serifed"
eszet = "longs-s-lig-serifless"
capital-delta = "curly"
lower-iota = "serifed-semi-tailed"
capital-lambda = "curly-serifless"
lower-lambda = "curly-turn"
lower-tau = "short-tailed"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
cyrl-ef = "split-serifless"
zero = "tall-slashed"
one = "base"
two = "curly-neck-serifless"
three = "two-arcs"
four = "closed-serifless"
five = "upright-arched-serifless"
six = "closed-contour"
seven = "straight-serifless"
eight = "crossing-asymmetric"
nine = "closed-contour"
tilde = "low"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "low"
paren = "normal"
brace = "curly"
guillemet = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "threefold"
dollar = "through-cap"
percent = "rings-continuous-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
pilcrow = "high"
cent = "through-cap"
micro-sign = "tailed-serifless"

[buildPlans.iosevka-ryanc]
family = "Iosevka RyanC"
spacing = "normal"
serifs = "sans"
noCvSs = true

[buildPlans.iosevka-ryanc.variants]
inherits = "buildPlans.template-sans"

[buildPlans.iosevka-ryanc.variants.italic]
a = "single-storey-tailed"
b = "toothed-serifless"
c = "serifless"
d = "tailed-serifless"
e = "rounded"
f = "tailed"
g = "single-storey-serifless"
h = "tailed-serifless"
i = "tailed-serifed"
j = "serifless"
k = "cursive-serifless"
l = "tailed-serifed"
m = "short-leg-tailed-serifless"
n = "tailed-serifless"
p = "eared-serifless"
q = "tailed-serifless"
r = "serifless"
s = "serifless"
t = "bent-hook"
u = "tailed-serifless"
v = "cursive-serifless"
w = "cursive-serifless"
x = "semi-chancery-curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"
long-s = "flat-hook-tailed-middle-serifed"
eszet = "longs-s-lig-tailed-serifless"
lower-iota = "serifed-semi-tailed"
cyrl-zhe = "cursive"
cyrl-el = "tailed"
cyrl-en = "tailed-serifless"
cyrl-u = "cursive-serifless"
cyrl-ef = "split-cursive"
cyrl-che = "tailed"
cyrl-yeri = "cursive"
cyrl-yery = "cursive-tailed"
cyrl-ya = "straight-tailed-serifless"

[buildPlans.iosevka-ryanc-web]
family = "Iosevka RyanC Web"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.iosevka-ryanc-web.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ryanc-web.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-ryanc-web.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-ryanc-web.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-ryanc-web.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.iosevka-ryanc-web.variants]
inherits = "buildPlans.iosevka-ryanc"

[buildPlans.iosevka-ryanc-aile]
family = "Iosevka RyanC Aile"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.iosevka-ryanc-aile.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ryanc-aile.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-ryanc-aile.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-ryanc-aile.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-ryanc-aile.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-ryanc-aile.variants]
inherits = "buildPlans.template-sans"

[buildPlans.iosevka-ryanc-aile.variants.design]
capital-i = "short-serifed"
capital-j = "serifless"
f = "flat-hook-serifless"
i = "serifless"
j = "flat-hook-serifless"
l = "hooky"
r = "compact-serifless"
t = "flat-hook"
at = "fourfold"

[buildPlans.iosevka-ryanc-etoile]
family = "Iosevka RyanC Etoile"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

[buildPlans.iosevka-ryanc-etoile.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ryanc-etoile.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-ryanc-etoile.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-ryanc-etoile.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-ryanc-etoile.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-ryanc-etoile.variants.design]
capital-a = "curly-base-serifed"
capital-b = "more-asymmetric-bilateral-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-g = "toothless-corner-serifed-capped"
capital-i = "serifed"
capital-m = "flat-bottom-serifed"
capital-w = "straight-flat-top-serifed"
f = "flat-hook-serifed"
i = "serifed-asymmetric"
j = "flat-hook-serifed"
l = "serifed-asymmetric"
t = "flat-hook"
w = "straight-flat-top-serifed"
long-s = "flat-hook-double-serifed"
eszet = "longs-s-lig-bottom-serifed"
capital-delta = "curly"
lower-iota = "serifed-flat-tailed"
capital-lambda = "curly-base-serifed"
lower-lambda = "curly-turn"
lower-mu = "tailed-serifed"
lower-tau = "flat-tailed"
cyrl-em = "flat-bottom-serifed"
zero = "tall-slashed"
one = "base"
two = "curly-neck-serifless"
three = "two-arcs"
four = "closed-serifless"
five = "upright-arched-serifless"
six = "closed-contour"
seven = "straight-serifed"
eight = "crossing-asymmetric"
nine = "closed-contour"
diacritic-dot = "square"
punctuation-dot = "square"
tilde = "low"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "low"
paren = "normal"
brace = "curly"
guillemet = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "fourfold"
dollar = "through-cap"
percent = "rings-continuous-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
pilcrow = "high"
cent = "through-cap"
micro-sign = "tailed-serifed"

[buildPlans.iosevka-ryanc-etoile.variants.italic]
b = "toothed-motion-serifed"
f = "flat-hook-tailed"
h = "tailed-motion-serifed"
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
m = "tailed-top-left-serifed"
n = "tailed-motion-serifed"
p = "eared-motion-serifed"
q = "tailed-motion-serifed"
v = "cursive-serifed"
w = "cursive-serifed"
long-s = "flat-hook-tailed-middle-serifed"
eszet = "longs-s-lig-tailed-serifless"

[buildPlans.iosevka-ryanc-term]
family = "Iosevka RyanC Term"
spacing = "term"
serifs = "sans"
noCvSs = true

[buildPlans.iosevka-ryanc-term.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ryanc-term.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-ryanc-term.variants]
inherits = "buildPlans.template-sans"

[buildPlans.iosevka-ryanc-term-ext]
family = "Iosevka RyanC TermExt"
spacing = "term"
serifs = "sans"
noCvSs = true

[buildPlans.iosevka-ryanc-term-ext.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ryanc-term-ext.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-ryanc-term-ext.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-ryanc-term-ext.widths.condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.iosevka-ryanc-term-ext.variants]
inherits = "buildPlans.template-sans"

[buildPlans.iosevka-ryanc-fixed]
family = "Iosevka RyanC Fixed"
spacing = "fixed"
serifs = "sans"
noCvSs = true

[buildPlans.iosevka-ryanc-fixed.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ryanc-fixed.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-ryanc-fixed.variants]
inherits = "buildPlans.template-sans"

[buildPlans.iosevka-ryanc-fixed-ext]
family = "Iosevka RyanC FixedExt"
spacing = "fixed"
serifs = "sans"
noCvSs = true

[buildPlans.iosevka-ryanc-fixed-ext.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ryanc-fixed-ext.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-ryanc-fixed-ext.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-ryanc-fixed-ext.widths.condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.iosevka-ryanc-fixed-ext.variants]
inherits = "buildPlans.template-sans"
