[buildPlans.iosevka-ryanc]                # <iosevka-ryanc> is your plan name
family = "Iosevka RyanC"                  # Font menu family name
# upright = ["upright-styles"]            # Uncomment this line to set styles for upright only
# italic = ["italic-styles"]              # Uncomment this line to set styles for italic only
# oblique = ["oblique-styles"]            # Uncomment this line to set styles for oblique only
# hintParams = ["-a", "sss"]              # Optional custom parameters for ttfautohint

# based on ss09
design = [
	'v-k-straight',
	'v-l-italic',
	'v-y-straight-turn',
	'v-capital-b-more-asymmetric',
	'v-capital-d-more-rounded',
	'v-zero-slashed',
	'v-one-base',
	'v-six-closed-contour',
	'v-nine-closed-contour',
	'v-asterisk-low',
	'v-at-threefold',
	'v-caret-low',
	'v-dollar-through',
	'v-numbersign-upright',
]
upright = [
	'v-i-hooky',
	'v-g-doublestorey',
]
italic = [
	'v-g-singlestorey',
]

###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.
#[buildPlans.iosevka-ryanc.weights.regular]
#shape = 400  # Weight for glyph shapes.
#menu  = 400  # Weight for the font's names.
#css   = 400  # Weight for webfont CSS.

#[buildPlans.iosevka-ryanc.weights.bold]
#shape = 700
#menu  = 700
#css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slopes would be built.

[buildPlans.iosevka-ryanc.slopes]
upright = "normal"
italic = "italic"
oblique = "oblique"

# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

[buildPlans.iosevka-ryanc.widths.normal]
shape = 500        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

[buildPlans.iosevka-ryanc.widths.extended]
shape = 576
menu  = 7
css   = "expanded"

# End width section
###################################################################################################
